src/main/java/fr/openent/lystore/export/Instruction.java
src/main/java/fr/openent/lystore/export/TabHelper.java
src/main/java/fr/openent/lystore/export/equipmentRapp/VerifBudgetTab.java
src/main/java/fr/openent/lystore/export/notificationEquipCP/LinesBudget.java
src/main/java/fr/openent/lystore/export/notificationEquipCP/NotifcationCpHelper.java
src/main/java/fr/openent/lystore/export/notificationEquipCP/NotificationLycTab.java
src/main/java/fr/openent/lystore/export/notificationEquipCP/RecapMarketGestion.java
src/main/java/fr/openent/lystore/helpers/ExcelHelper.java

Mlystor 292/export notification equipment cp

---

src/main/resources/sql/034-lystore-fix-project-delete.sql

Adding ore in the trigger of project deletion

updating function of delete trigger  off project

---

src/main/resources/i18n/fr.json
src/main/resources/public/import/skeletonIntitule.csv
src/main/resources/public/sass/global/_lystore-specifics.scss
src/main/resources/public/template/administrator/campaign/title/import-titles-form.html
src/main/resources/public/template/administrator/instruction/instruction-form.html
src/main/resources/public/template/customer/campaign/basket/manage-basket.html
src/main/resources/public/template/customer/campaign/catalog/equipment-detail.html
src/main/resources/public/ts/controllers/viewer/catalog.ts

Fixing some bugs + adding update button "comment" to add clarity when creating/update Purse

FIX/MYLSTOR-305 MYLSTOR-302 MYLSTOR-321 MYLSTOR-299

---

deployment/lystore/conf.json.template
src/main/java/fr/openent/lystore/Lystore.java
src/main/java/fr/openent/lystore/controllers/ExportController.java
src/main/java/fr/openent/lystore/export/ExportLystoreWorker.java
src/main/java/fr/openent/lystore/export/Instruction.java
src/main/java/fr/openent/lystore/export/TabHelper.java
src/main/java/fr/openent/lystore/export/equipmentRapp/AnnexeDelibTab.java
src/main/java/fr/openent/lystore/export/equipmentRapp/ComptaTab.java
src/main/java/fr/openent/lystore/export/equipmentRapp/ListForTextTab.java
src/main/java/fr/openent/lystore/export/notificationEquipCP/LinesBudget.java
src/main/java/fr/openent/lystore/export/notificationEquipCP/NotificationLycTab.java
src/main/java/fr/openent/lystore/export/notificationEquipCP/RecapMarketGestion.java
src/main/java/fr/openent/lystore/export/subventionEquipment/Market.java
src/main/java/fr/openent/lystore/export/subventionEquipment/Subventions.java
src/main/java/fr/openent/lystore/helpers/ExcelHelper.java
src/main/java/fr/openent/lystore/helpers/MongoHelper.java
src/main/java/fr/openent/lystore/security/AccessExportDownload.java
src/main/java/fr/openent/lystore/service/ExportService.java
src/main/java/fr/openent/lystore/service/impl/DefaultExportServiceService.java
src/main/java/fr/openent/lystore/service/impl/DefaultStructureService.java
src/main/resources/public/ts/controllers/administration/export.ts
src/main/resources/public/ts/model/export.ts

lystoreIterationWorker=10 à mettre dans conf.properties

Mlystor 328/refacto worker

---

src/main/resources/public/template/administrator/equipment/manage-equipments.html
src/main/resources/public/ts/controllers/main.ts

- Correctif qui traitera la gestion du $digest quand on met à jour l'instructon du eventer des equipements afin d'éviter un bloquage 
(l'image empêche le chargement d'une page comme elle est bloquée par le $digest)
- Correctif json dans le ngClass

fix(infra-front 3.12): MLYSTOR-508 Fix $digest handler + bad json intepretation

---

src/main/resources/public/ts/controllers/administration/configuration.ts

Même problème que https://github.com/OPEN-ENT-NG/lystore/pull/51 au niveau du `$scope.$apply` qui bloque la page html

fix(infra-front 3.12): MLYSTOR-515 Fix $digest/apply handler 

---

src/main/resources/public/ts/controllers/viewer/basket.ts

fix(angular): Remove check number with boolean

---

src/main/resources/public/template/administrator/operation/operation-form.html
src/main/resources/public/ts/controllers/administration/operation.ts

Replace date placeholder by day date in creation form operation.

Mlystor 442/ Creation operation date form

---

src/main/resources/public/template/administrator/instruction/instruction-form.html
src/main/resources/public/ts/controllers/administration/instruction.ts

Replace date placeholder by day date in creation form instruction.

Mlystor 443/creation date instruction

---

src/main/resources/public/sass/global/_lystore-specifics.scss
src/main/resources/public/template/administrator/orderRegion/order-region-create-form.html
src/main/resources/public/ts/directives/contenteditable.ts
src/main/resources/public/ts/directives/index.ts

If there is a ngModel, this directive "contenteditable" will listen for change events to enable binding.
At the end, write data to the model.

fix(orderRegionCreate): MLYSTOR-413 fix ng-model in span, contenteditable

---

src/main/resources/public/sass/global/_lystore-specifics.scss
src/main/resources/public/template/administrator/orderRegion/order-region-create-form.html
src/main/resources/public/ts/directives/contenteditable.ts
src/main/resources/public/ts/directives/index.ts

Need to do a buildFront before testing

fix(orderRegionCreate): MLYSTOR-413 fix css textarea comment, to feat with global theme page

---

src/main/resources/i18n/fr.json
src/main/resources/public/sass/global/_lystore-specifics.scss
src/main/resources/public/template/administrator/campaign/purse/manage-purse.html
src/main/resources/public/template/customer/campaign/catalog/equipment-detail.html
src/main/resources/public/ts/controllers/main.ts

Do a buildFront before testing

feat(catalogPrice): MLYSTOR-505 added HT and taxes price & css changes

---

src/main/java/fr/openent/lystore/model/InstructionStatus.java
src/main/java/fr/openent/lystore/service/impl/DefaultInstructionService.java
src/main/resources/i18n/fr.json
src/main/resources/jsonschema/instruction.json
src/main/resources/public/sass/global/_lystore-specifics.scss
src/main/resources/public/template/administrator/instruction/instruction-cp-rejected-lightbox.html
src/main/resources/public/template/administrator/instruction/instruction-form.html
src/main/resources/public/template/administrator/instruction/manage-instruction.html
src/main/resources/public/ts/controllers/administration/instruction.ts
src/main/resources/public/ts/controllers/administration/operation.ts
src/main/resources/public/ts/model/OrderClient.ts
src/main/resources/public/ts/model/instruction.ts
src/main/resources/sql/058-update-adopted-cp.sql

TODO : 
buildFront before testing for CSS to apply.

feat(instructionStatus): MLYSTOR-563 handle rejected status for cp

---

src/main/resources/public/template/administrator/campaign/purse/manage-purse.html
src/main/resources/public/ts/controllers/administration/purse.ts

On screen : campaign management, manage pot :
- fix sorting for the two last column

fix(sortingPot): MLYSTOR-564 fix sorting for purse table

---

src/main/resources/public/sass/global/_lystore-specifics.scss

On screen generate order :
- Search and select now fitting with the content
TODO : 
- buildFront before testing

fix(createOrder): MLYSTOR-441 fix display create order label search-and-select

---

src/main/resources/public/sass/global/_lystore-specifics.scss
src/main/resources/public/template/customer/campaign/catalog/equipment-detail.html

DONE : 
- Add spacing for picture
TODO :
- buildFront before testing

fix(PriceCatalog): MLYSTOR-505 fix css for spacing picture

---

src/main/resources/public/template/administrator/order/order-waiting.html
src/main/resources/public/ts/controllers/administration/orders.ts
src/main/resources/public/ts/model/OrderClient.ts

Infinite scroll added to order-waiting to improve html creation time

feat(orderWaiting): MLYSTOR-556 add infinite scroll to reduce html creation time

---

src/main/resources/public/template/administrator/order/order-update-add-files.html

Now look and work like create order popup add file

fix(orderUpdate): MLYSTOR-414 fix popup to feat with global theme

---

src/main/resources/public/sass/global/_lystore-specifics.scss
src/main/resources/public/template/administrator/orderRegion/order-region-create-form.html

TODO before test :
- buildFront

fix(orderRegionComment): MLYSTOR-413 fix input type & css

---

src/main/java/fr/openent/lystore/controllers/EquipmentController.java
src/main/java/fr/openent/lystore/controllers/InstructionController.java
src/main/java/fr/openent/lystore/model/EquipmentStatus.java
src/main/java/fr/openent/lystore/service/EquipmentService.java
src/main/java/fr/openent/lystore/service/InstructionService.java
src/main/java/fr/openent/lystore/service/impl/DefaultEquipmentService.java
src/main/java/fr/openent/lystore/service/impl/DefaultInstructionService.java
src/main/resources/public/ts/controllers/administration/export.ts
src/main/resources/public/ts/controllers/administration/instruction.ts
src/main/resources/public/ts/model/export.ts
src/main/resources/sql/061-fix-allOperationOrders-view.sql

TODO : Faire attention au numéro du script SQL avant d'accepter la PR

feat(filters): MLYSTOR-585 Add and fix filters for Export, Instruction and Equipment

---

LICENSE
README.md

ajout de la nouvelle licence et d'une description technique.
merge après vérification des PO.

docs: #CO-1632 add new licence and technical description

---

gradle.properties
gulpfile.js
package.json
src/main/resources/view-src/lystore.html
src/main/resources/view-src/parameter.html

prepare 4.6.0 migration
compile and check with new springboard

chore: prepare 4.6.0 migration

---

.github/pull_request_template.md

Ajout du template pull request

chore(action): add pull request template

---

src/main/java/fr/openent/lystore/service/impl/DefaultOrderService.java

Describe your changes
Correct tax on options in BC
Checklist tests
Faire un BC avec un équipement possédant des options
Issue ticket number and link
https://jira.support-ent.fr/browse/MLYSTOR-646
Checklist before requesting a review (magic string, indentation, comment/documentation...)
I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in Checklist tests)
I have performed a self-review of my code
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation (API Doc etc...) - (must specify in Description for target version)
If it is a consequent feature, I have added thorough tests.
I have added tests that prove my fix is effective or that my feature works
Any dependent …

fix(BC)#MLYSTORE-657:fix tax on bc options

---

src/main/resources/public/template/parameter/parameter-main.html
src/main/resources/public/ts/controllers/parameter/parameter-main.controller.ts

ajout d'une navbar dans parameter
https://jira.support-ent.fr/browse/MLYSTOR-626

fix(Lystore)#MLYSTOR-654:add add navbar in parameter

---

deployment/lystore/conf.j2
deployment/lystore/conf.json.template
src/main/java/fr/openent/lystore/constants/ExportConstants.java
src/main/java/fr/openent/lystore/controllers/OrderController.java
src/main/java/fr/openent/lystore/export/validOrders/BC/BCExport.java
src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidation.java
src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportAfterValidationStructure.java
src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportBeforeValidationStructure.java
src/main/java/fr/openent/lystore/export/validOrders/BC/BCExportDuringValidation.java
src/main/java/fr/openent/lystore/export/validOrders/PDF_OrderHElper.java
src/main/java/fr/openent/lystore/service/impl/DefaultExportPDFService.java
src/main/resources/public/template/pdf/BC.xhtml
src/main/resources/public/template/pdf/BC_CSF.xhtml
src/main/resources/public/template/pdf/BC_Struct.xhtml

Use node Pdf genreator for better css
https://jira.support-ent.fr/browse/MLYSTOR-646
Lystore -> générer les bons de commandes -> sélectionner une commande puis faire "Export BC" ou "Export CSF" ou "Export BC par établissement"

fix(BC-CSF)#MLYSTOR-646:use of node-pdf to better css

---

src/main/resources/public/template/parameter/active-structure/active-structure.html

align checkbox with head
need pr : https://github.com/CGI-OPEN-ENT-NG/entcore-css-lib/pull/33
Lystore ( as SupedAdmin) > Activation Etablissement
https://jira.support-ent.fr/browse/MLYSTOR-664

fix(ActiveStructure):#MLYSTORE-664 align checkbox with title

---

deployment/lystore/2.0.1/ExportIndex.js

Add index status on lystore export

feat(Export): #MLYSTORE-592  add index on status

---

src/main/java/fr/openent/lystore/service/impl/DefaultEquipmentService.java
src/main/resources/i18n/fr.json
src/main/resources/public/template/customer/campaign/catalog/catalog-list.html
src/main/resources/public/ts/controllers/main.ts
src/main/resources/public/ts/core/constants/equipment.status.const.ts
src/main/resources/public/ts/directives/equipment-card/equipment-card.directive.ts
src/main/resources/public/ts/directives/equipment-card/equipment-card.html
src/main/resources/public/ts/directives/index.ts
src/main/resources/public/ts/filters/currencyFilter.ts
src/main/resources/public/ts/model/Equipment.ts

now display ht price and tax on catalog view as a client 
check if correct display 
https://jira.support-ent.fr/browse/MLYSTOR-595

feat(Catalog-Client): #MLYSTORE-595 add tax and price ht in view client

---

src/main/java/fr/openent/lystore/service/impl/DefaultOrderService.java
src/main/resources/sql/065-lystore-order-total-with-region.sql

update sql fuction to work with order region 
Vérifier si les montants dans les demandes en attentes n'ont pas été modifiés
Vérifier si les montants dans les demandes validées n'ont pas été modifiés
Vérifier si les montants dans les demandes envoyées n'ont pas été modifiés
https://jira.support-ent.fr/browse/MLYSTOR-587

feat #MLYSTORE-587 : update orderTotal to works with order region

---

src/main/java/fr/openent/lystore/service/impl/DefaultEquipmentService.java

order catalog 
https://jira.support-ent.fr/browse/MLYSTOR-667

feat(Catalog-Client) #MLYSTORE-667: order equipment

---

src/main/java/fr/openent/lystore/constants/CommonConstants.java
src/main/java/fr/openent/lystore/constants/LystoreBDD.java
src/main/java/fr/openent/lystore/controllers/PurseController.java
src/main/java/fr/openent/lystore/model/Purse.java
src/main/java/fr/openent/lystore/model/Structure.java
src/main/java/fr/openent/lystore/model/utils/Domain.java
src/main/java/fr/openent/lystore/service/PurseService.java
src/main/java/fr/openent/lystore/service/StructureService.java
src/main/java/fr/openent/lystore/service/impl/DefaultPurseService.java
src/main/java/fr/openent/lystore/service/impl/DefaultStructureService.java
src/main/java/fr/openent/lystore/utils/OrderUtils.java
src/test/java/fr/openent/lystore/service/DefaultPurseServiceTest.java

ajout de 3 colones supplémentaires dans l'export (Cagnotte initiale, total des commandes, Nom Etab)
Faire un export et vérifier que : Cagnotte = Cagnotte initiale - total des commandes)
https://jira.support-ent.fr/browse/MLYSTOR-596

feat(PurseExport) #MLYSTORE-596 : add 3 column to csv  

---

src/main/java/fr/openent/lystore/constants/CommonConstants.java
src/main/java/fr/openent/lystore/export/ExportLystoreWorker.java
src/main/java/fr/openent/lystore/export/campaign/CampaignExport.java
src/main/java/fr/openent/lystore/export/campaign/extractionOrder/ExtractionOrder.java
src/main/java/fr/openent/lystore/export/campaign/extractionOrder/RecapStructOrder.java
src/main/java/fr/openent/lystore/export/helpers/ExportHelper.java

take config name
https://jira.support-ent.fr/browse/MLYSTOR-679

fix(CampaignExport) #MLYSTOR-679: export can change name via config

---

src/main/resources/public/template/customer/campaign/order/orders-by-equipment.html
src/main/resources/public/template/customer/campaign/order/orders-by-project.html
src/main/resources/public/ts/controllers/main.ts
src/main/resources/public/ts/controllers/viewer/order-list.ts
src/main/resources/public/ts/model/Order.ts
src/main/resources/public/ts/model/OrderClient.ts
src/main/resources/sql/067.order_total_round.sql

gestion des arrondis
https://jira.support-ent.fr/browse/MLYSTOR-677

fix(OrderCLient) #MLYSTOR-677: update function to better round

---

src/main/resources/i18n/fr.json
src/main/resources/public/template/administrator/order/order-update-form.html

New label in update form of an orderClient
need : https://github.com/CGI-OPEN-ENT-NG/entcore-css-lib/pull/44
https://jira.support-ent.fr/browse/MLYSTOR-674

fix(OrderClientUpdate) #MLYSTOR-674: new label for better understanding

---

src/main/resources/i18n/fr.json
src/main/resources/public/template/administrator/order/order-update-form.html

new i18n
https://jira.support-ent.fr/browse/MLYSTOR-674

fix(orderClientUpdate) #MLYSTORE-674: new i18n

---

src/main/java/fr/openent/lystore/export/campaign/extractionOrder/ExtractionOrder.java

more fixes
https://jira.support-ent.fr/browse/MLYSTOR-675

fix(orderClientUpdate) #MLYSTORE-674: region name

---

src/main/resources/public/ts/model/Equipment.ts

check if undefined too
https://jira.support-ent.fr/browse/MLYSTOR-675

fix(Equipment): #MLYSTOR-702 now check if undefined too

---

src/main/java/fr/openent/lystore/Lystore.java
src/main/java/fr/openent/lystore/controllers/LystoreController.java
src/main/java/fr/openent/lystore/logging/Actions.java

add llystore to statistics
https://github.com/opendigitaleducation/statistics/pull/20
https://jira.support-ent.fr/browse/MLYSTOR-703

feat(Lystore): #MLYSTOR-703 add lystore to statistics

---

src/main/java/fr/openent/lystore/constants/CommonConstants.java
src/main/java/fr/openent/lystore/constants/LystoreBDD.java
src/main/java/fr/openent/lystore/controllers/TitleController.java
src/main/java/fr/openent/lystore/model/Structure.java
src/main/java/fr/openent/lystore/model/Title.java
src/main/java/fr/openent/lystore/service/TitleService.java
src/main/java/fr/openent/lystore/service/impl/DefaultTitleService.java
src/main/resources/public/template/administrator/campaign/title/import-titles-form.html
src/main/resources/public/template/administrator/campaign/title/manage-title.html
src/main/resources/public/template/administrator/campaign/title/title-deletion-confirmation.html
src/main/resources/public/ts/controllers/administration/title.ts
src/main/resources/public/ts/model/Structure.ts
src/main/resources/public/ts/model/Title.ts
src/main/resources/public/ts/services/app/title.service.ts
src/test/java/fr/openent/lystore/service/DefaultTitltServiceTest.java

back for 426
https://confluence.support-ent.fr/pages/viewpage.action?pageId=158599486
Si suppression de tout les intitulés d un établissement , il doit disparaitre de l'écran
https://jira.support-ent.fr/browse/MLYSTOR-426

feat(Title): #MLYSTOR-426 add multi delete title 

---

src/main/resources/public/template/administrator/campaign/title/manage-title.html
src/main/resources/public/ts/controllers/administration/title.ts

disable button when already all selected
https://jira.support-ent.fr/browse/MLYSTOR-426

feat(Title) :#MLYSTOR-426 disable all select

---

src/main/resources/public/ts/controllers/administration/orders.ts

fix a bug when no instruction make not possible to open affect to operations
https://jira.support-ent.fr/browse/MLYSTOR-707

fix(OrderWaiting):#MLYSTOR-707: bug when no instruction in bdd

---

src/main/java/fr/openent/lystore/service/impl/DefaultOrderService.java
src/main/resources/sql/069-reject-date.sql

ajout d une date de refus et de cloture de demande
https://jira.support-ent.fr/browse/MLYSTOR-710

feat(Order) :#MLYSTORE-710 add date of reject order and done date

---

src/main/java/fr/openent/lystore/constants/CommonConstants.java
src/main/java/fr/openent/lystore/constants/EnumConstant.java
src/main/java/fr/openent/lystore/constants/LystoreBDD.java
src/main/java/fr/openent/lystore/model/InstructionStatus.java
src/main/java/fr/openent/lystore/service/OrderRegionService.java
src/main/java/fr/openent/lystore/service/OrderService.java
src/main/java/fr/openent/lystore/service/impl/DefaultInstructionService.java
src/main/java/fr/openent/lystore/service/impl/DefaultOperationService.java
src/main/java/fr/openent/lystore/service/impl/DefaultOrderRegionService.java
src/main/java/fr/openent/lystore/service/impl/DefaultOrderService.java
src/main/resources/sql/070-update-status-order.sql

reject an instruction now rejet the orders linked to said instruction
https://jira.support-ent.fr/browse/MLYSTOR-709

feat(Instruction):#MLYSTOR-709 now reject a cp in instruction rejects order too

---

src/main/resources/public/template/customer/campaign/basket/manage-basket.html
src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.html

i18n change 
https://jira.support-ent.fr/browse/MLYSTOR-687

feat(Order/Basket): #MLYSTOR-687 now display price TTC as label

---

src/main/resources/public/template/administrator/campaign/campaign_form.html

i18n change 
https://jira.support-ent.fr/browse/MLYSTOR-682

fix(Campaign): #MLYSTOR-682 change i18n to "save"

---

src/main/java/fr/openent/lystore/service/impl/DefaultOrderService.java
src/main/resources/public/ts/directives/order-client-display-viewer/order-client-display-viewer.html

fix(OrderOptions) #MLYSTOR-686: now display "no options" and fix bug bc/csf

---

src/main/java/fr/openent/lystore/service/impl/SqlUtils.java
src/main/resources/sql/071-updateOrderOperation.sql

fix more sql functions
MLYSTOR-686

fix(OrderOptions): #MLYSTOR-686 fix sql function for options

---

src/main/java/fr/openent/lystore/constants/ExportConstants.java
src/main/java/fr/openent/lystore/export/validOrders/PDF_OrderHElper.java
src/main/resources/public/ts/directives/bc-preview/bc-preview.directive.ts
src/main/resources/public/ts/directives/bc-preview/bc-preview.html

display price in bc and  Bc preview with 2 digits and a comma 
https://jira.support-ent.fr/browse/MLYSTOR-683

feat(BC): #MLYSTOR-683 now display all price with 2 digits and a comma

---

src/main/java/fr/openent/lystore/constants/ExportConstants.java
src/main/java/fr/openent/lystore/export/validOrders/PDF_OrderHElper.java
src/main/resources/public/ts/directives/bc-preview/bc-preview.directive.ts
src/main/resources/public/ts/directives/bc-preview/bc-preview.html

fix(BC): now every price with 2 digits after coma 

---

src/main/java/fr/openent/lystore/constants/LystoreBDD.java
src/main/java/fr/openent/lystore/export/campaign/extractionOrder/ExtractionOrder.java
src/main/java/fr/openent/lystore/security/AccessUpdateOrderOnClosedCampaigne.java
src/main/java/fr/openent/lystore/service/impl/DefaultCampaignService.java
src/main/resources/jsonschema/campaign.json
src/main/resources/public/template/administrator/campaign/manage-campaign.html
src/main/resources/public/template/customer/campaign/campaign-detail.html
src/main/resources/public/template/customer/campaign/campaign-list.html
src/main/resources/public/template/customer/campaign/order/orders-by-equipment.html
src/main/resources/public/template/customer/campaign/order/orders-by-project.html
src/main/resources/public/ts/controllers/administration/configuration.ts
src/main/resources/public/ts/controllers/viewer/campaigns-list.ts
src/main/resources/public/ts/model/Campaign.ts
src/main/resources/public/ts/services/Campaign.ts
src/main/resources/public/ts/services/index.ts
src/main/resources/sql/073-campaign-table-delete-accessible.sql

remove acessible and check with view and function if campaign is open 
-Une campagne automatique doit être ouvert entre ses dates de fermeture et d ouverture et fermée en dehors
-Une campagne manuelle est fermée par défaut et ne possède qu une date d ouverture lorsqu elle est ouverte 
https://jira.support-ent.fr/browse/MLYSTOR-688

fix(Campaign) new date handle or campaigns 

---

src/main/resources/public/ts/controllers/administration/configuration.ts

fix campaign automatic when start date is after now
https://jira.support-ent.fr/browse/MLYSTOR-688

fix(campaign): #MLYSTOR-688 fix creation automatic campaign

---

src/main/java/fr/openent/lystore/service/impl/DefaultCampaignService.java
src/main/resources/public/ts/model/Campaign.ts

manual campaign doesn't have a start date at creation.
Changements API : https://confluence.support-ent.fr/display/LYS/Campagne
-La campagne manuelle est fermée à la création
-La campagne manuelle n'a pas de date de début à la création 
https://jira.support-ent.fr/browse/MLYSTOR-660

fix (Campaign): #MLYSTOR-660  fix manual campaigns

---

src/main/resources/public/ts/controllers/administration/configuration.ts

fix a bugwhen 1 day appart it wont work
https://jira.support-ent.fr/browse/MLYSTOR-688

fix(Campaign): #MLYSTORE-688 fix gap date when 1 day appart

---

src/main/resources/public/ts/controllers/administration/configuration.ts

replace after by sameOrAfter
https://jira.support-ent.fr/browse/MLYSTOR-688

fix(Campaign): #MLYSTORE-688 fix gap date when 1 day appart again

---

src/main/resources/public/ts/controllers/administration/orders.ts

cannot longer validate done orders
https://jira.support-ent.fr/browse/MLYSTOR-734

fix(OrdersValid): #MLYSTORE-734 cannot longer validate done orders

---

src/main/resources/public/ts/model/Campaign.ts

handle future auto campaign to manual
https://jira.support-ent.fr/browse/MLYSTOR-660

fix(OrdersValid): #MLYSTORE-660 handle future auto campaign to manual

---

src/main/java/fr/openent/lystore/service/impl/DefaultPurseService.java
src/main/resources/jsonschema/purse.json
src/main/resources/public/template/administrator/campaign/purse/edit-purse-form.html
src/main/resources/public/ts/controllers/administration/purse.ts
src/main/resources/public/ts/model/Purse.ts

fix update purses
https://jira.support-ent.fr/browse/MLYSTOR-711

fix(Purse): #MLYSTOR-711 fix update purses

---

src/main/resources/public/ts/controllers/administration/configuration.ts

start_date is null when updating manual to automatic
https://jira.support-ent.fr/browse/MLYSTOR-740

fix(Purse) #MLYSTOR-740 : fix start_date is null

---

src/main/resources/public/ts/model/OrderClient.ts

fix invalid dates due to function call with old code
-no more invalid dates in ordersWaiting
https://jira.support-ent.fr/browse/MLYSTOR-740

fix(OrdersWaiting) #MLYSTOR-738 : fix invalid dates due to function call

---

src/main/resources/public/ts/model/Purse.ts
src/main/resources/public/ts/model/__mocks__/entcore.ts
src/main/resources/public/ts/services/__test__/purse.service.test.ts

fix broken tests
https://jira.support-ent.fr/browse/MLYSTOR-740

Fix(test) #MLYSTORE-740 fix broken tests

---

src/main/java/fr/openent/lystore/controllers/PurseController.java
src/main/java/fr/openent/lystore/service/PurseService.java
src/main/java/fr/openent/lystore/service/impl/DefaultPurseService.java
src/main/resources/public/ts/controllers/administration/purse.ts

update amount take total_order into account 
https://jira.support-ent.fr/browse/MLYSTOR-711

fix(Purse) #MLYSTOR-711 : fix update hen negative amount

---

src/main/resources/public/template/administrator/campaign/purse/manage-purse.html
src/main/resources/public/ts/services/app/admin/purse.service.ts

-fix a bug when error message were still displayerd after closing a popup and reopening it
-fix a bug when difference when checking amount were wrong
https://jira.support-ent.fr/browse/MLYSTOR-711

fix(Purse) MLYSTOR-711 : fix check and onclose popup

---

src/main/java/fr/openent/lystore/export/validOrders/PDF_OrderHElper.java
src/main/resources/public/template/pdf/BC.xhtml
src/main/resources/public/template/pdf/BC_Struct.xhtml

breakline works in pdf now 
-BC
-BC par établissement
https://jira.support-ent.fr/browse/MLYSTOR-684

fix(BC) #MLYSTORE-684: fix bc brealkine in adress

---

src/main/resources/public/ts/model/Purse.ts

display fix bug where displaying names instead of uai
https://jira.support-ent.fr/browse/MLYSTOR-746

fix(Purses) #MLYSTOR-746 display fix bug where displaying name

---

src/main/java/fr/openent/lystore/export/campaign/extractionOrder/ExtractionOrder.java

fix typo in "Commentaire"
https://jira.support-ent.fr/browse/MLYSTOR-708

fix(exportCampaign) #MLYSTOR-708 : fix typo in "Commentaire"

---

src/main/resources/i18n/fr.json
src/main/resources/public/template/customer/campaign/basket/project-confirmation.html
src/main/resources/public/template/customer/campaign/order/update-project-confirmation.html
src/main/resources/public/ts/controllers/viewer/order-list.ts
src/main/resources/public/ts/controllers/viewer/project.ts

display placeholder instead of "getPlaceHolder"
https://jira.support-ent.fr/browse/MLYSTOR-685

fix(Project) #MLYSTOR-685 : display placeholder instead of "getPlaceHolder"

---

src/main/resources/i18n/fr.json
src/main/resources/public/template/customer/campaign/basket/project-confirmation.html
src/main/resources/public/template/customer/campaign/order/update-project-confirmation.html

limit character in textarea for description of a project
https://jira.support-ent.fr/browse/MLYSTOR-732

fix(Project) #MLYSTOR-732 : max limit character

---

src/main/resources/public/sass/components/directives/_order-preview.scss
src/main/resources/public/ts/directives/bc-preview/bc-preview.html

\n in html for address in bc preview 
https://jira.support-ent.fr/browse/MLYSTOR-684

fix(BC) #MLYSTOR-684 : \n in html for address

---

src/main/java/fr/openent/lystore/service/impl/DefaultOperationService.java
src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.html
src/main/resources/public/ts/model/OrderClient.ts

fix a bug where priority and project name was not displayed 
https://jira.support-ent.fr/browse/MLYSTOR-764
https://jira.support-ent.fr/browse/MLYSTOR-741

fix(OrdersWaiting) : #MLYSTOR-764 fix a bug where priority was not displayed

---

src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.directive.ts
src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.html

fix rank to have the same as client side 
https://jira.support-ent.fr/browse/MLYSTOR-764

fix(DisplayOrderListTables): #MLYSTOR-764 fix rank

---

src/main/resources/public/ts/directives/display-order-list/TabFields.ts
src/main/resources/public/ts/directives/display-order-list/display-order-list-table/display-order-list-table.directive.ts
src/main/resources/public/ts/model/OrderClient.ts

fix order by rank by casting it to number
https://jira.support-ent.fr/browse/MLYSTOR-764

fix(Priority): #MLYSTOR-764 fix order by rank by casting it to number
